#
# Makefile for dibvwr
#

PROJECT = dibvwr
OBJS	= dibvwr.o dibwin.o dibfunc.o dbvabout.o dibopen.o windbg.o \
          winfuncs.o cdlgtool.o bmpfile.o
LIBS	= -lcomdlg32
RESOURCES = dibvwr.rc

include ..\..\rsxntmak.gnu

CFLAGS = -O -I.
