#define IDD_TARGET_NAME    100
#define IDD_TARGET_WIN32   101
#define IDD_OPT_GCCOTHER   102
#define IDD_TARGET_DLL     102
#define IDD_TARGET_LIB     103
#define IDD_TARGET_RSX     104
#define IDD_TARGET_EMX     105
#define IDD_DDE_EDITOR     200
#define IDD_DDE_SERVICE    201
#define IDD_DDE_TOPIC      202
#define IDD_DDE_FILEOPEN   204
#define IDD_DDE_GOTO       205
#define IDD_DDE_MARKLINE   206
#define IDD_DDE_COMBO      209
#define IDD_EDIT           300
#define IDD_OPT_COMBO      500
#define IDD_OPT_DEBUG      501
#define IDD_OPT_MULTI      502
#define IDD_OPT_PRINT      503
#define IDD_OPT_PIPE       504
#define IDD_OPT_BIND       506
#define IDD_OPT_INC        600
#define IDD_OPT_MACROS     601
#define IDD_OPT_UMACROS    602
#define IDD_OPT_CPPOTHER   603
#define IDD_OPT_INCFILE    604
#define IDD_OPT_INCMAC     605
#define IDD_OPT_NOSTDINC   606
#define IDD_OPT_OPTNO      700
#define IDD_OPT_OPT1       701
#define IDD_OPT_OPT2       702
#define IDD_OPT_OPT3       703
#define IDD_OPT_486        704
#define IDD_OPT_EBP        705
#define IDD_OPT_WARNNO     710
#define IDD_OPT_WARNALL    711
#define IDD_OPT_WARNEXT    712
#define IDD_OPT_WARNPED    713
#define IDD_OPT_WARNERR    714
#define IDD_OPT_GNU        720
#define IDD_OPT_ANSI       721
#define IDD_OPT_TRADI      722
#define IDD_OPT_SIGCHAR    723
#define IDD_OPT_UNSIGBIT   724
#define IDD_OPT_WRITESTR   725
#define IDD_OPT_CC1OTHER   726
#define IDD_OPT_LIBS       800
#define IDD_OPT_LDIR       801
#define IDD_OPT_NOSTDO     802
#define IDD_OPT_NOSTDLIB   803
#define IDD_OPT_LDOTHER    804
